### ISSUE TITLE
Connection to "python.org" failed

### ISSUE THREAD

**Issue by jgherb** [mitmproxy/mitmproxy#1498]
##### Steps to reproduce the problem:

1. Start mitmdump on my server
2. Configure Browser "Firefox 38"
3. Navigate in Browser to website "www.python.org"

##### What is the expected behavior?
Website should be loaded

##### What went wrong?
Firefox error: "Your connection is no secure"

##### Any other comments? What have you tried so far?
Other websites like google.com or facebook.com work properly.
Mitmdump output:
[my ip]:[my port]: clientconnect
[my ip]:[my port]: clientdisconnect
: GET https://www.python.org/ HTTP/2.0
 << Zombie Stream
[my ip]:[my port]: clientconnect
[my ip]:[my port]: clientdisconnect
: GET https://www.python.org/ HTTP/2.0
 << Zombie Stream
[my ip]:[my port]: clientconnect
[my ip]:[my port]: clientdisconnect
: GET https://www.python.org/ HTTP/2.0
 << Zombie Stream

---

Mitmproxy Version: 0.18
Operating System: Ubuntu 16.04

**Comment by Kriechi** [comment]
It works well with `curl`.
Firefox seems to produce an error which results in an `invalid stream id` protocol error.
I will investigate further.

**Comment by Kriechi** [comment]
**Update:**
The same error happens on https://h2o.examp1e.net/
It is a problem with mapping priority information between `client <-> proxy <-> server` which involves a lot of stream id manipulation.

**Comment by Kriechi** [comment]
This is actually a bug on the server - so there is nothing we can do.

The bug is already reported upstream and a fix is available.
ref: https://github.com/python-hyper/hyper-h2/issues/302#issuecomment-242128527
ref: https://github.com/h2o/h2o/pull/1043

**Comment by worenga** [comment]
@Kriechi 

I came across this issue with several sites, while doing some Internet measurements with h2-servers in the wild with using a firefox and mitmproxy.
Unfortunately, waiting for them to adopt the fix is not an option.

I noticed that mitmproxy works fine in version v0.17, but with 0.18 the error mentioned above appears, which is weird as it is supposed to be an h2o server issue?

**Comment by worenga** [comment]
Strangely enough i traced down the frames in 0.17 and 0.18 for python.org and they seem to be exactly the same, however in 0.18 we get the GOAWAY:

0.17:
```
127.0.0.1:58840: clientconnect
00000c040000000000000400020000000500004000
SettingsFrame(Stream: 0; Flags: None):   (stream:  0 ) -> length:  12
00000408000000000000bf0001
WindowUpdateFrame(Stream: 0; Flags: None): 00000000  (stream:  0 ) -> length:  4
00000502000000000300000000c8
PriorityFrame(Stream: 3; Flags: None): 0000000000  (stream:  3 ) -> length:  5
0000050200000000050000000064
PriorityFrame(Stream: 5; Flags: None): 0000000000  (stream:  5 ) -> length:  5
0000050200000000070000000000
PriorityFrame(Stream: 7; Flags: None): 0000000000  (stream:  7 ) -> length:  5
0000050200000000090000000700
PriorityFrame(Stream: 9; Flags: None): 0000000000  (stream:  9 ) -> length:  5
00000502000000000b0000000300
PriorityFrame(Stream: 11; Flags: None): 0000000000  (stream:  11 ) -> length:  5
00015901250000000d0000000b1f82048163418bf1e3c2f5fa4ce7a973d937877abad07f66a281b0dae053fafc087ed4e11db526dfb5339aab7ca9e5e72271afb52cef71a79707f6a62293a9d810020004015309ac2ca7f2c34f2e0f53b0497ca589d34d1f43aeba0c41a4c7a98f33a69a3fdf9a68fa1d75d0620d263d4c79a68fbed00177febe58f9fbed00177b518b2d4b70ddf45abefb4005db508d9bd9abfa5242cb40d25fa523b360ab8a2b5348e06441005a65f5db79e136f3af32b85a75a68227996970b4eb4d044f32d2e169d69a089e65a5c37e968a2b534c703220802d32faef2e102e169d69a089e65a1f308b8a2b5349206441005a65ff7f00ba8a2b534fb819104016997d70b4eb4d044f32d2e15c2bda9a488b20fea43585227fbff96a69212a83fa90d61489feffe5a9a494c907f551ea2ff71f31868a2b534a600f4092b6b9ac1c8558d520a4b6c2ad617b5a54251f810f5887a47e561cc5801f
HeadersFrame(Stream: 13; Flags: END_STREAM, PRIORITY, END_HEADERS): 0000000000  (stream:  13 ) -> length:  345
00000408000000000d00be0000
WindowUpdateFrame(Stream: 13; Flags: None): 00000000  (stream:  13 ) -> length:  4
00000c040000000000000300000064000401000000
SettingsFrame(Stream: 0; Flags: None):   (stream:  0 ) -> length:  12
000000040100000000
SettingsFrame(Stream: 0; Flags: ACK):   (stream:  0 ) -> length:  0
000000040100000000
SettingsFrame(Stream: 0; Flags: ACK):   (stream:  0 ) -> length:  0
000000040100000000
SettingsFrame(Stream: 0; Flags: ACK):   (stream:  0 ) -> length:  0
000000040100000000
SettingsFrame(Stream: 0; Flags: ACK):   (stream:  0 ) -> length:  0
00000408000000000000ff0001
WindowUpdateFrame(Stream: 0; Flags: None): 00000000  (stream:  0 ) -> length:  4
000213010400000001886196e4593e941054dc5ad41002e28005c035700153168dff5f92497ca589d34d1f6a1271d882a60b532acf7f408bf2b4b60e92ac7ad263d48f89dd0e8c1ab6e4c5934f408df2b128193aa163f72d9394727f8fc5a7829bcb659e94d760d249ca94ff52848fd24a8f7c880ae153b8eca8c89f5501304089f2b20b6772c8b47ebf8d20c93956a09e82113ab67bdcff4085f2b10649cb044d4953534089f2b10649cab4e64a3f01307b85bc73f5317f408baed8e83116ea5f4b566a91ffb201a47e561cc581c003ed43544a2d90bbad8ef9e919aa47da959aa59138c4db907f3c8e6e5b7d64d5c748df34e3ba436ddd79dfcc7d28373dcff1f1c316ac96c8d6bba17a0fe7ed4acd52c89c626dc83f96ef3dd7bf0032fe63dbc6ca1b15f017f776295ad55743b59a743c9a7d6fa38b357083f9fb52b354b227189b720fe5bbcf75efc00cbf98f6f1b286c57c05fddd8a56b555d0ed669d0f269f5be8e2cd5c20fe7ed4acd52c89c626dc83f9a2f575e1ed1f5b28cace0271c30f529ab07fb69ae233e5e1ea98ead43c1c3aba9c1c20fe7ed4acd52c89c626dc83f9dfc2fd56034603e564f2bbfef9d06bba2ef1c375a626ca8eedfbd4ee4f37dfff7ccfcb241fcfda959aa59138c4db907f3e5ad9ef5eebcf04199b609a3a4606f652d7566ef86fddda9aa37c9a98ab072637c8d41fcfdf7899a47e561cc581c640e880007da86a8945b21775b1df3d2335480f0d053437343333
//... Delivery of site omitted
```

master
```
127.0.0.1:58834: clientconnect
00000c040000000000000400020000000500004000
SettingsFrame(Stream: 0; Flags: None):   (stream:  0 ) -> length:  12
00000408000000000000bf0001
WindowUpdateFrame(Stream: 0; Flags: None): 00000000  (stream:  0 ) -> length:  4
00000502000000000300000000c8
PriorityFrame(Stream: 3; Flags: None): 0000000000  (stream:  3 ) -> length:  5
0000050200000000050000000064
PriorityFrame(Stream: 5; Flags: None): 0000000000  (stream:  5 ) -> length:  5
0000050200000000070000000000
PriorityFrame(Stream: 7; Flags: None): 0000000000  (stream:  7 ) -> length:  5
0000050200000000090000000700
PriorityFrame(Stream: 9; Flags: None): 0000000000  (stream:  9 ) -> length:  5
00000502000000000b0000000300
PriorityFrame(Stream: 11; Flags: None): 0000000000  (stream:  11 ) -> length:  5
00015901250000000d0000000b1f82048163418bf1e3c2f5fa4ce7a973d937877abad07f66a281b0dae053fafc087ed4e11db526dfb5339aab7ca9e5e72271afb52cef71a79707f6a62293a9d810020004015309ac2ca7f2c34f2e0f53b0497ca589d34d1f43aeba0c41a4c7a98f33a69a3fdf9a68fa1d75d0620d263d4c79a68fbed00177febe58f9fbed00177b518b2d4b70ddf45abefb4005db508d9bd9abfa5242cb40d25fa523b360ab8a2b5348e06441005a65f5db79e136f3af32b85a75a68227996970b4eb4d044f32d2e169d69a089e65a5c37e968a2b534c703220802d32faef2e102e169d69a089e65a1f308b8a2b5349206441005a65ff7f00ba8a2b534fb819104016997d70b4eb4d044f32d2e15c2bda9a488b20fea43585227fbff96a69212a83fa90d61489feffe5a9a494c907f551ea2ff71f31868a2b534a600f4092b6b9ac1c8558d520a4b6c2ad617b5a54251f810f5887a47e561cc5801f
HeadersFrame(Stream: 13; Flags: END_STREAM, PRIORITY, END_HEADERS): 0000000000  (stream:  13 ) -> length:  345
00000408000000000d00be0000
WindowUpdateFrame(Stream: 13; Flags: None): 00000000  (stream:  13 ) -> length:  4
00000c040000000000000300000064000401000000
SettingsFrame(Stream: 0; Flags: None):   (stream:  0 ) -> length:  12
000000040100000000
SettingsFrame(Stream: 0; Flags: ACK):   (stream:  0 ) -> length:  0
000000040100000000
SettingsFrame(Stream: 0; Flags: ACK):   (stream:  0 ) -> length:  0
000000040100000000
SettingsFrame(Stream: 0; Flags: ACK):   (stream:  0 ) -> length:  0
000000040100000000
SettingsFrame(Stream: 0; Flags: ACK):   (stream:  0 ) -> length:  0
00002a0700000000000000000b00000005696e76616c69642073747265616d20696420696e2048454144455253206672616d65
GoAwayFrame(Stream: 0; Flags: None): 0000000000000000  (stream:  0 ) -> length:  42
127.0.0.1:58834: HTTP/2 connection terminated by server: error code: 5, last stream id: 11, additional data: invalid stream id in HEADERS frame
127.0.0.1:58834: clientdisconnect
```

which leads me to believe that this might be some sort of race condition

**Comment by Kriechi** [comment]
You are about half right... 😉 

If I remember correctly the problem here was PRIORITY information that Firefox sends and python.org has to accept.
mitmproxy 0.17 didn't respect PRIORITY at all - it just got silently swallowed.
mitmproxy master now does respect that, and tries to forward PRIORITY with proper stream ids to the server. However, this is where python.org now runs into a bug, because the stream ids do not line up to their believe of how it should look like. 

Last thing I heard through back channels was, that they are aware of their RFC7540-section-5.3 violation and will deploy a fix at some point in the near future.

**Comment by worenga** [comment]
@Kriechi , thank you for your reply.

However, I tried using nghttp without a proxy on python org and they imitate Firefox Priority behavior and there it works on python.org, so isnt that a sign that something is still not right here?

Here is a dump of nghttp

$nghttp https://www.python.org -vn
[  0.086] Connected
The negotiated protocol: h2
[  0.170] send SETTINGS frame <length=12, flags=0x00, stream_id=0>
          (niv=2)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
[  0.170] send PRIORITY frame <length=5, flags=0x00, stream_id=3>
          (dep_stream_id=0, weight=201, exclusive=0)
[  0.170] send PRIORITY frame <length=5, flags=0x00, stream_id=5>
          (dep_stream_id=0, weight=101, exclusive=0)
[  0.170] send PRIORITY frame <length=5, flags=0x00, stream_id=7>
          (dep_stream_id=0, weight=1, exclusive=0)
[  0.170] send PRIORITY frame <length=5, flags=0x00, stream_id=9>
          (dep_stream_id=7, weight=1, exclusive=0)
[  0.170] send PRIORITY frame <length=5, flags=0x00, stream_id=11>
          (dep_stream_id=3, weight=1, exclusive=0)
[  0.170] send HEADERS frame <length=43, flags=0x25, stream_id=13>
          ; END_STREAM | END_HEADERS | PRIORITY
          (padlen=0, dep_stream_id=11, weight=16, exclusive=0)
          ; Open new stream
          :method: GET
          :path: /
          :scheme: https
          :authority: www.python.org
          accept: */*
          accept-encoding: gzip, deflate
          user-agent: nghttp2/1.14.0-DEV
[  0.207] recv SETTINGS frame <length=12, flags=0x00, stream_id=0>
          (niv=2)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):16777216]
[  0.207] recv SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
[  0.207] send SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
[  0.209] recv (stream_id=13) :status: 200
[  0.210] recv (stream_id=13) date: Wed, 21 Sep 2016 07:18:48 GMT
[  0.210] recv (stream_id=13) content-type: text/html; charset=utf-8
[  0.210] recv (stream_id=13) x-frame-options: SAMEORIGIN
[  0.210] recv (stream_id=13) x-clacks-overhead: GNU Terry Pratchett
[  0.210] recv (stream_id=13) accept-ranges: bytes
[  0.210] recv (stream_id=13) via: 1.1 varnish
[  0.210] recv (stream_id=13) age: 1887
[  0.210] recv (stream_id=13) x-served-by: cache-lhr6320-LHR
[  0.210] recv (stream_id=13) x-cache: HIT
[  0.210] recv (stream_id=13) x-cache-hits: 3
[  0.210] recv (stream_id=13) vary: Cookie
[  0.210] recv (stream_id=13) public-key-pins: max-age=600; includeSubDomains; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="5C8kvU039KouVrl52D0eZSGf4Onjo4Khs8tmyTlV3nU="; pin-sha256="5C8kvU039KouVrl52D0eZSGf4Onjo4Khs8tmyTlV3nU="; pin-sha256="lCppFqbkrlJ3EcVFAkeip0+44VaoJUymbnOaEUk7tEU="; pin-sha256="TUDnr0MEoJ3of7+YliBMBVFB4/gJsv5zO7IxD9+YoWI="; pin-sha256="x4QzPSC810K5/cMjb05Qm4k3Bw5zBn4lTdO/nEW/Td4=";
[  0.210] recv (stream_id=13) strict-transport-security: max-age=63072000; includeSubDomains
[  0.210] recv (stream_id=13) content-length: 47433
[  0.210] recv HEADERS frame <length=532, flags=0x04, stream_id=13>
          ; END_HEADERS
          (padlen=0)
          ; First response header
[  0.251] recv DATA frame <length=16384, flags=0x00, stream_id=13>
[  0.295] recv DATA frame <length=16384, flags=0x00, stream_id=13>
[  0.295] recv DATA frame <length=14665, flags=0x01, stream_id=13>
          ; END_STREAM
[  0.295] send GOAWAY frame <length=8, flags=0x00, stream_id=0>
          (last_stream_id=0, error_code=NO_ERROR(0x00), opaque_data(0)=[])
```

**Comment by Kriechi** [comment]
Disclaimer: python.org is probably not the only one - they just happen to run a popular site so we found the issue on their site first 😃  So please don't feel insulted or bad-mouthed here.

Yes, you are right - it is a the bug in python.org is triggered by mitmproxy due to a slightly different PRIORITY information handling. Since all streams run in parallel, and Firefox just starts sending a bunch of PRIORITY frames for stream that don't exist yet, mitmproxy has to map this non-existant stream ids to new ones, in order to not cause collisions at a later point in time. For example, this means mitmproxy then sends a PRIORITY frame for a stream with ID 42. Then Firefox starts an actual stream by sending a HEADERS frame with stream id 3. All perfectly valid.

Now python.org complains about this, because it thinks "I already say PRIORITY for stream 42, so creating a new stream with a lower id is not allowed". And this is not correct. According to the RFC, sending PRIORITY frames does not change the state of a stream, and therefore this error in invalid.

As far as I know, we are working according to the RFC - and the python.org webserver does not.

So, we have three options:
  * we revert back to the old behaviour of silently swallowing PRIORITY frames,
  * we add a massive change to the way we handle PRIORITY frames and new streams, and try to bend everything until as python.org accepts it, which is a big intrusion in the data flow through the proxy,
  * or we try and push the nice sysadmins over at python.org to fix their webserver 😉

**Comment by worenga** [comment]
Ah thank you i think i get behind the cause of this behaviour now.

Stupid Beginner Question: Why do we need the mapping and cannot reuse alway's the client's stream id? Or further how are stream id collisions even possible? Pushed Streams differ from client streams by parity.

**Comment by Kriechi** [comment]
Pushed streams play no role in this case.
Imagine Firefox sending 3 requests: `/index.html`, `style.css`, and `code.js`.
Assume these three streams get ids: 3, 5, 7

Now mitmproxy sees all the requests and calls the hooks so the user can intercept, modify or block the requests - whatever is possible with mitmproxy can happen now - before the request is actually forwarded to the server.

Lets assume mitmproxy should replace the a header for the `/index.html` request. This might take a bit - maybe the new value has to be computed, or read from disk, or even fetched from a different service (eg. a database or another API endpoint in the backend).
This means the first request with id 3 has to wait until it can be forwarded to the server.

Now, stream 5 and 7 can be passed through unchanged. Since the HTTP/2 protocol dictates that once a certain stream id has been used to open a new stream, all ids lower than that are invalid from now on.

So, stream 5 and 7 have been opened and forwarded to the server.
Stream 3 is still being modified or something - so we cannot simply use stread id 3 because it would already be invalid.
Therefore mitmproxy needs to assign a new stream id for this request to conform with the RFC.
So mitmproxy remapped stream 3 to 9 and sends it to the server.

The server thinks at this point it has gotten three requests: 5, 7 and 9. And then it sends responses for these streams to mitmproxy.
The client thinks at this point it has sent three requests: 3, 5, and 7.
mitmproxy keeps track of all these mappings and now has to translate it back and forth every time a new frame is received from one of the endpoints.

This is pretty simple and straightforward for HEADERS and DATA frames - because the directly operate on opened streams.
WINDOW_UPDATE, PRIORITY, PUSH_PROMISE and others are a bit more tricky, because the mapping might be unknown since non has been created yet. So we need to preemptively create a new mapping to satisfy the "all lower ids than the latest are invalid" restriction.

I hope this makes it a bit clearer what the underlying behaviour is - HTTP/2 is very strict and but at the same time pretty simple to follow, once all the state changes etc are understood 😉

**Comment by Kriechi** [comment]
FYI: 

We had a similar case with Twitter and found a h2-related bug in their h2 web-stack.
And the kind guys over at Twitter just fixed their webserver and now are fully compliant with the RFC: https://github.com/mitmproxy/mitmproxy/issues/1310#issuecomment-248971807
They even went through the trouble of actually testing with mitmproxy! Really great! 👍 

So things do move forward - and we just have to wait.
