### ISSUE TITLE
Mitmproxy cannot decode WBXML

### ISSUE THREAD

**Issue by elorz007** [mitmproxy/mitmproxy#2638]
##### Steps to reproduce the problem:
On 
1. Open a request that contains WBXML (for example, sync requests of Apple Mail app)
2. In both the request and response tabs I see `Couldn’t parse: falling back to raw`

##### Any other comments? What have you tried so far?
I tried different versions of python with virtualenv, no difference.
I tried installing from pip and from brew, no difference.

I tried version 0.17.1 binary directly: worked (but I would prefer a not so old version)
I tried version 2.0.2 binary directly: didn't work.

##### System information

Mitmproxy version: 2.0.2 (release version)
Python version: 3.6.3
Platform: Darwin-16.7.0-x86_64-i386-64bit
SSL version: OpenSSL 1.1.0f  25 May 2017
Mac version: 10.12.6 ('', '', '') x86_64

(I only found this https://discourse.mitmproxy.org/t/cant-decode-wbxml/621 but there is no response there...)

**Comment by ujjwal96** [comment]
Will it be possible for you to share the WBXML file?
Both the versions, 2.0.2 and 0.17 use the same decoder https://github.com/mitmproxy/mitmproxy/tree/master/mitmproxy/contrib/wbxml 
If it works in 0.17 it should work in 2.0.2

**Comment by elorz007** [comment]
This is an example of WBXML
hexdump:
```
0000000 03 01 6a 00 00 0d 45 48 03 32 34 30 00 01 49 4a
0000010 4b 03 31 37 00 01 4c 03 45 6d 61 69 6c 00 01 01
0000020 4a 4b 03 37 00 01 4c 03 45 6d 61 69 6c 00 01 01
0000030 4a 4b 03 31 31 00 01 4c 03 43 6f 6e 74 61 63 74
0000040 73 00 01 01 4a 4b 03 32 35 00 01 4c 03 4e 6f 74
0000050 65 73 00 01 01 4a 4b 03 31 35 00 01 4c 03 4e 6f
0000060 74 65 73 00 01 01 4a 4b 03 31 34 00 01 4c 03 4e
0000070 6f 74 65 73 00 01 01 4a 4b 03 31 32 00 01 4c 03
0000080 4e 6f 74 65 73 00 01 01 4a 4b 03 31 30 00 01 4c
0000090 03 43 61 6c 65 6e 64 61 72 00 01 01 4a 4b 03 31
00000a0 00 01 4c 03 54 61 73 6b 73 00 01 01 4a 4b 03 33
00000b0 00 01 4c 03 54 61 73 6b 73 00 01 01 4a 4b 03 32
00000c0 00 01 4c 03 54 61 73 6b 73 00 01 01 01 01
00000ce
```
or raw:
```
\x03\x01j\x00\x00
EH\x03240\x00\x01IJK\x0317\x00\x01L\x03Email\x00\x01\x01JK\x037\x00\x01L\x03Email\x00\x01\x01JK\x0311\x00\x01L\x03Contacts\x00\x01
\x01JK\x0325\x00\x01L\x03Notes\x00\x01\x01JK\x0315\x00\x01L\x03Notes\x00\x01\x01JK\x0314\x00\x01L\x03Notes\x00\x01\x01JK\x0312\x00
\x01L\x03Notes\x00\x01\x01JK\x0310\x00\x01L\x03Calendar\x00\x01\x01JK\x031\x00\x01L\x03Tasks\x00\x01\x01JK\x033\x00\x01L\x03Tasks\
x00\x01\x01JK\x032\x00\x01L\x03Tasks\x00\x01\x01\x01\x01
```

Which is correctly decoded in 0.17.1 as
```
<?xml version="1.0" ?>
<Ping>
    <HeartbeatInterval>240</HeartbeatInterval>
    <Folders>
        <Folder>
            <Id>17</Id>
            <Class>Email</Class>
        </Folder>
        <Folder>
            <Id>7</Id>
            <Class>Email</Class>
        </Folder>
        <Folder>
            <Id>11</Id>
            <Class>Contacts</Class>
        </Folder>
        <Folder>
            <Id>25</Id>
            <Class>Notes</Class>
        </Folder>
        <Folder>
            <Id>15</Id>
            <Class>Notes</Class>
        </Folder>
        <Folder>
            <Id>14</Id>
            <Class>Notes</Class>
        </Folder>
        <Folder>
            <Id>12</Id>
            <Class>Notes</Class>
        </Folder>
        <Folder>
            <Id>10</Id>
            <Class>Calendar</Class>
        </Folder>
        <Folder>
            <Id>1</Id>
            <Class>Tasks</Class>
        </Folder>
        <Folder>
            <Id>3</Id>
            <Class>Tasks</Class>
        </Folder>
        <Folder>
            <Id>2</Id>
            <Class>Tasks</Class>
        </Folder>
    </Folders>
</Ping>
```
But it is failed to decode in version 2.0.2:
![screen shot 2017-12-01 at 18 28 20](https://user-images.githubusercontent.com/3601038/33495127-79ada6c0-d6c5-11e7-9039-2ae08f0c6e8d.png)


And I checked that the content (by exporting it with command "b") is exactly the same

**Comment by mhils** [comment]
Very helpful, thanks!

**Comment by iamblinking** [comment]
I also find this decode error in version 2.02 and 0.9.2

**Comment by kajojify** [comment]
It seems to be fixed in the latest release and also in master branch.
I used pathoc/pathod and these wbxml examples https://github.com/davidpshaw/PyWBXMLDecoder/tree/master/wbxml_samples to test it.

Mitmproxy **v2.0.2**:
![image](https://user-images.githubusercontent.com/20267977/35778736-0708c1a2-09cb-11e8-99f8-dca5c618cd81.png)

Mitmproxy **v3.0.0**:
![image](https://user-images.githubusercontent.com/20267977/35778753-4139f65c-09cb-11e8-90dd-00775b383573.png)

@mhils are we still fixing bugs for **v2.0.2** and earlier?

**Comment by mhils** [comment]
@kajojify: no, we don't - 3.0 is around the corner. :-)

**Comment by kajojify** [comment]
Then since it is fixed in 3.0rc2, I think it can be closed :) 
A way to make sure, that wbxml is decoded (or isn't):
1. Run mitmproxy.
2. Create a folder and put into it any file from https://github.com/davidpshaw/PyWBXMLDecoder/tree/master/wbxml_samples.
3. `pathod -a '/=200:b<"response-4569.wbxml"' -d ~/yourfolder/`
4. `pathoc -c localhost:9999 localhost:8080 'get:/'`
5. In mitmproxy: `enter` the flow -> `response` -> `m` -> `wbxml`
Maybe this isn't the shortest way, but I used it :)

**Comment by elorz007** [comment]
I checked a real-life scenario (an iPhone with iOS 11.2.5 and an exchange mail account configured). When doing any action with the Mail.app I could correctly see the wbxml content correctly parsed.

**Comment by mhils** [comment]
👍

**Comment by user185953** [comment]
This issue is back.
Parsing fails due to "KeyError: '0,2'" while .format-ing UNKOWN_TAG_
I created a [pull request on PyWBXMLDecoder](https://github.com/davidpshaw/PyWBXMLDecoder/pull/4)  The unknown tag that causes this problem is Codepage 0x16, Tag 0x15 returned by server
