### ISSUE TITLE
mitm.it cert not working for iOS v. 15.3.1

### ISSUE THREAD

**Issue by diezcode** [mitmproxy/mitmproxy#5166]
#### Problem Description
I try to setup everything to see the traffic on my iphone. the problem is that I can't download the iOS cert and I don't
see it in the iphone settings under certifications to activate it.

#### Steps to reproduce the behavior:
1. Upgrade mobile to iOS version 15.3.1
2. setup proxy settings 
3. try to install the iOS certificate from mitm.it

#### System Information
Paste the output of "mitmproxy --version" here.
7.0.4

**Comment by mhils** [comment]
The following configuration works fine for me:

 - iOS 15.3.1
 - mitmproxy development snapshot (https://mitmproxy.org/downloads/#branches/main/)
 - A newly generated certificate in `~/.mitmproxy` (delete existing cert and then restart the new mitmproxy version)

I think there are two possible reasons why it may not work for you:

 - Your mitmproxy CA was generated quite a while ago with older policies, which are now not supported anymore. Regenerating should fix it.
 - We do something right in the latest dev snapshots that doesn't work on 7.0.4. We should have a release out soon anyhow. :)

**Comment by sz-ashik440** [comment]
Facing similar issue.
Steps:
* Run mitmproxy(version 10.1.6) from m1 mac(macOS-14.1.2) 
* Then configured Proxy to `manual` mode in iphone(iphone 11 , iOS17.2)
* Then when tried to open mitm.it form safari, this shows no internet.
* Then got Airdrop the `mitmproxy-ca-cert.pem` file from `~/.mitmproxy` folder and added to the phone. Still can't connect to the internet.

**Comment by felixenpr** [comment]
> Facing similar issue. Steps:
> 
> * Run mitmproxy(version 10.1.6) from m1 mac(macOS-14.1.2)
> * Then configured Proxy to `manual` mode in iphone(iphone 11 , iOS17.2)
> * Then when tried to open mitm.it form safari, this shows no internet.
> * Then got Airdrop the `mitmproxy-ca-cert.pem` file from `~/.mitmproxy` folder and added to the phone. Still can't connect to the internet.

I have this issue too.
