### ISSUE TITLE
Memory Leak in WireGuard Mode

### ISSUE THREAD

**Issue by mhils** [mitmproxy/mitmproxy#5861]
#### Problem Description
WireGuard and Windows Proxy Mode have a memory leak somewhere.

#### Steps to reproduce the behavior:
1. `python -m http.server`
2. `mitmdump --mode osproxy:curl` (or WireGuard)
3. `while true: curl http://127.0.0.1:8000/`

@decathorpe suspects `TcpStream.read()` :)

refs https://github.com/awestlake87/pyo3-asyncio/issues/84

**Comment by meitinger** [comment]
This may be a stupid question, but if returning `bytes` from `TcpStream.read` somehow increments the refcount beyond 1, has it been tried to change the signature and function to read into a `bytearray` instead, returning the number of bytes read? I'm not an expert in Rust, but it looks like `pyo3::types::PyByteArray` should support mutability.

If that works, a small wrapper around `TcpStream` in Python could then call the function with a `bytearray` and provider the other `read` signature returning `bytes`.

**Comment by decathorpe** [comment]
I didn't even know `bytearray` was a thing :) It might solve the problem, but it might also cause the `int` object that's returned to be leaked, instead ... no idea if both classes are affected in the same way in this case.

But if I understand your suggestion correctly, you'd change `Tcpstream.read(int) -> bytes` to `TcpStream.read(bytearray, int) -> int`, and just modify the bytearray instead of returning a new `bytes` object?

**Comment by meitinger** [comment]
If the return type can just be a `u32`, I hope there's no refcounting going on then.
The signature could just be `TcpStream.read(bytearray) -> int`, as `PyByteArray` seems to have `len` function, so we don't need to have another parameter for that. Maybe also change the name to `readinto` to be more ['pythonic'](https://docs.python.org/3/library/io.html#io.RawIOBase.readinto).

**Comment by mhils** [comment]
That's certainly a nice workaround, but also only just that. I'd be strongly in favor of tracking down where the extra Py_INCREF is coming from. 😛

**Comment by decathorpe** [comment]
> If the return type can just be a `u32`, I hope there's no refcounting going on then.

I think refcounting *will* be involved, because PyO3 automatically adds conversion from non-Python types to Python objects when wrapping Rust functions. The only thing this would gain us in that case would be that the leaked objects are much smaller (i.e. one `int` object instead of one `bytes` object, possibly thousands of bytes big).

**Comment by meitinger** [comment]
> I'd be strongly in favor of tracking down where the extra Py_INCREF is coming from. 😛

That's definitely the better option, yes :)

> I think refcounting will be involved.

In case the additional refs for `bytes` cannot be tracked down and `int`s also get more refs, then it's still possible to return `py.None()` (which will always be the same object, so it doesn't matter if it has more refs), encode the length in the first four bytes of the `bytearray` and recover it with `int.from_bytes`.

---

Regarding https://github.com/decathorpe/mitmproxy_wireguard/blob/e06ec83d1983447a930d89be9aa7689e67bf5c81/src/python/tcp_stream.rs#L46 I wonder if not storing the result of `PyBytes::new(...).into_py(...)` with `let` but rather return `Ok` in `Python::with_gil` might make a difference (if it's possible), i.e.
```
pyo3_asyncio::tokio::future_into_py(py, async move {
    let data = rx.await.map_err(connection_closed)?;
    Python::with_gil(|py| Ok(PyBytes::new(py, &data).into_py(py)));
})
```

**Comment by decathorpe** [comment]
> Regarding https://github.com/decathorpe/mitmproxy_wireguard/blob/e06ec83d1983447a930d89be9aa7689e67bf5c81/src/python/tcp_stream.rs#L46 I wonder if not storing the result of `PyBytes::new(...).into_py(...)` with `let` but rather return `Ok` in `Python::with_gil` might make a difference (if it's possible), i.e.

Damn 😮 you figured it out! ✨ ✨

I suspected that something like this might be the cause of the problem - I saw similar issue reports where holding the GIL or not made the difference ... but it didn't dawn on me that the construction of the `PyBytes` might also be affected here.

I applied the change you suggested (moving `PyBytes::new` call to where the GIL is held), and the memory leak seems to be gone. Previously, my benchmark workload resulted in memory usage growing up to ~2.6 GB, but now it tops out at ~200 MB and drops back down to ~13 MB after the last connection is closed. Meh, that was a lot of time I wasted on debugging this issue 😆

**Comment by decathorpe** [comment]
I released a new version of mitmproxy-wireguard, which should now hopefully contain the fix for this issue (and another, but much smaller memory accumulation problem): https://pypi.org/project/mitmproxy-wireguard/0.1.20/

@mhils, can you confirm that the memory leak is gone with the new version?

**Comment by decathorpe** [comment]
I can also submit a PR with equivalent changes to https://github.com/mitmproxy/mitmproxy_rs once they have been confirmed to fix the problem.

**Comment by meitinger** [comment]
My gut feeling was/is, that calling `Ok` `within_gil` will wrap (hide) the object in way that Rust doesn't touch it anymore afterwards. Returning and storing it with `let`, on the other hand, feels like adding another reference.
(Again, totally not an expert in Rust, but if this were C# and I'd be dealing with a COM object, I'd do the same thing. :)

**Comment by mhils** [comment]
Looks like this is still leaking to some extent unfortunately. Using the following patch:
```diff
diff --git a/mitmproxy/proxy/server.py b/mitmproxy/proxy/server.py
index d101188e4..0c446d0d1 100644
--- a/mitmproxy/proxy/server.py
+++ b/mitmproxy/proxy/server.py
@@ -10,6 +10,7 @@ import abc
 import asyncio
 import collections
 import logging
+import sys
 import time
 import traceback
 from collections.abc import Awaitable
@@ -280,6 +281,7 @@ class ConnectionHandler(metaclass=abc.ABCMeta):
         while True:
             try:
                 data = await reader.read(65535)
+                print(f"{sys.getrefcount(data)=}")
                 if not data:
                     raise OSError("Connection closed by peer.")
             except OSError:
```

I still see refcounts >2 with the changes applied to `mitmproxy_rs`.

**Comment by decathorpe** [comment]
If you check the refcount immediately after getting the data, some cleanup of the tokio task might not have happened yet, so calling `getrefcount(data)` immediately after calling `reader.read()` is a bit race-y. In my testing all memory gets freed eventually.

**Comment by claddyk** [comment]
hey @mhils, if this issue is still open(which it appears to), can I work on this?

**Comment by mhils** [comment]
Sure!

**Comment by decathorpe** [comment]
This has been fixed in mitmproxy_wireguard here (released since v0.1.20, almost a year ago):
https://github.com/decathorpe/mitmproxy_wireguard/commit/d589e0a2d82f39716df560802eef319f487d1c0c

Has this not been merged into mitmproxy-rs yet?

**Comment by mhils** [comment]
Should be fixed here then: https://github.com/mitmproxy/mitmproxy_rs/blob/main/mitmproxy-rs/src/tcp_stream.rs#L47

If noone can repro, let's close this? :)
